version: "3.9"

services:
  coredns:
    image: coredns/coredns:1.11.1
    container_name: coredns
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - ./Corefile:/etc/coredns/Corefile:ro
    command: ["-conf", "/etc/coredns/Corefile"]
    networks:
      macvlan-coredns:
        ipv4_address: 172.20.100.10

networks:
  macvlan-coredns:
    external: true