services:
  coredns:
    image: coredns/coredns:1.11.1
    container_name: coredns
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - ./Corefile:/etc/coredns/Corefile:ro
    command: ["-conf", "/etc/coredns/Corefile"]
    networks:
      macvlan_net:
        ipv4_address: 172.20.100.10 # пример IP

networks:
  macvlan_net:
    external: true
    name: macvlan_net